#' Script to check all the data stored in the SIRENO database of on shore sampling is properly exported to
#' the RDBES file, which is uploaded to RDBES database.
#' The data is compared at different levels:
#' - Number of hauls by rim stratum
#' - Number of trips by rim stratum
#' - Number of individuals by species
#'
#' The files required to run this script are:
#' - IEORDBES_H1_ICES_MARCO_H1.csv, the H1 RDBES file containing the data to be uploaded to the RDBES database,
#' generated in SIRENO.
#' - IEODESMAREASIRENO_OAB_2023_ICES.TXT, the SIRENO report containing the trips stored in SIRENO database
#' - IEODESLANCESIRENO_OAB_2023_ICES.TXT, the SIRENO report containing the hauls stored in SIRENO database. Must
#' be generated with the option 'only hauls'.
#' - IEODESCAPTURASIRENO_OAB_2023_ICES.TXT, the SIRENO report containing the catches stored in SIRENO database.
#' Must be generated with the option 'by category'.
#' - IEODESTALLASSIRENO_OAB_2023_ICES.TXT, the SIRENO report containing the lengths stored in SIRENO database.
#' Must be generated by categories.
#'
#' Those files must be stored in 'input' folder.
#'
#' Other data sets required are stored in 'data' folder.


# LOAD LIBRARIES ----
library(sapmuebase)
library(dplyr)

# utils functions
source("R/report_RDBES_SIRENO_utils.R")

# Load David Currie functions
source("R/RDBES_Functions.R")
# Temporary fix required for a function from icesVocab - otherwise the function breaks when it tries
# to download the EDMO code list (or any list containing carriage returns)
source("R/tempIcesVocabFix.R")

# Function to read the file. In this case, the reference data and the list of
# required tables for each hierarchy are already downloaded from RDBES github.
# The first time this function is used, its necessary to download it. See
# ReadExchangeFileExample_WKRDBEST2.R file to do it.
source("R/readRDBESFile.R")

# IMPORTANT: Hack to stop write.csv changing numbers to scientific notation
options(scipen = 500) # big number of digits


# GLOBAL VARIABLES ----
DATA_PATH <- file.path(getwd(), "data")
INPUT_PATH <- file.path(getwd(), "input")


# FILENAMES ----
strata_file <- "maestro_estrato_tecnico-estrato_rim_SAP__rdbes_estratorim.csv"
species_file <- "rdbes_especies_2024_03_19.txt"
species_not_upload <- "species_not_upload_rdbes_2021__rdbes_especies_not_upload.csv"


# ⬇️⬇️⬇️ YOU ONLY HAVE TO CHANGE THE FOLLOWING NAMES OF FILES ⬇️⬇️⬇️ ----
rdbes_file <- "IEORDBES_H1_ICES_MARCO_H1.csv" # Must end with the hierarchy followed by ".csv"

trips_file <- "IEODESMAREASIRENO_OAB_2023_ICES.TXT"
hauls_file <- "IEODESLANCESIRENO_OAB_2023_ICES.TXT"
catches_file <- "IEODESCAPTURASIRENO_OAB_2023_ICES.TXT"
lengths_file <- "IEODESTALLASSIRENO_OAB_2023_ICES.TXT"
# ⬆️⬆️⬆️ YOU ONLY HAVE TO CHANGE THE PREVIOUS NAMES OF FILES ⬆️⬆️⬆️  ----


# IMPORT FILES ----
## strata ----
strata <- read.csv2(file.path(DATA_PATH, strata_file))
strata <- strata[strata$Scheme == "at-sea", ]

## species ----
sps_rdbes <- read.csv2(file.path(DATA_PATH, species_file), sep = ",")
# remove Dipturus flossada from sps_rdbes (I don't know why it is there)
sps_rdbes <- sps_rdbes[sps_rdbes$ESPSIRENO != "Dipturus flossada", ]

## not upload species ----
sps_not_upload <- read.csv2(file.path(DATA_PATH, species_not_upload))

## rdbes files ----
# TODO: test the import_test.R script to import by my own the rdbes files (work in progress)
# start_time <- Sys.time()
# h1 <- readRDBESFile(file.path(INPUT_PATH, rdbes_file))
# end_time <- Sys.time()
# time_taken <- end_time - start_time
# time_taken
# saveRDS(h1, paste0(INPUT_PATH, "/h1.rds"))
h1 <- readRDS(paste0(INPUT_PATH, "/h1.rds"))

### rdbes individual tables ----
h1_tables <- getAllRequiredTables()
h1_tables <- h1_tables$H1[1:length(h1_tables$H1) - 1]
DE <- h1$DE
SD <- h1$SD
VS <- h1$VS
FT <- h1$FT
FO <- h1$FO
SS <- h1$SS
SA <- h1$SA
FM <- h1$FM

## sireno files ----
trips <- importOABTrips(trips_file, INPUT_PATH)
hauls <- importOABHauls(hauls_file, INPUT_PATH)
catches <- importOABCatches(catches_file, INPUT_PATH)
lengths <- importOABLengths(lengths_file, INPUT_PATH)


# COMPLETE TABLES ----
## h1 complete table ----
h1_complete <- Reduce(function(x, y) {
  c_name <- paste0(x, "id")

  if (class(y) == "character") {
    y <- get(y)
  }

  result <- merge(get(x), y, by = c_name, all.x = TRUE)
  return(result)
}, h1_tables, right = TRUE)

h1_complete$FMnumberAtUnit <- as.numeric(h1_complete$FMnumberAtUnit)

empty_columns <- get_empty_columns(h1_complete)

h1_clean <- h1_complete[, !names(h1_complete) %in% empty_columns]

## sireno hauls_catches table ----
hauls_catches <- merge(hauls, catches, all.x = TRUE)
hauls_catches <- merge(hauls_catches,
  strata,
  by = "ESTRATO_RIM",
  all.x = TRUE
)


# COMPARE RDBES UPLOADED VS SIRENO ----
## RDBES summary ----
h1_summary <- h1_clean %>%
  select(
    DEsamplingScheme, DEyear, DEstratumName,
    FTunitName,
    FOnationalFishingActivity, FOsequenceNumber, FOvalidity, FOcatchReg, FOmetier6, FOsampled,
    SScatchFraction
  ) %>%
  unique() %>%
  group_by(
    DEsamplingScheme, DEyear, DEstratumName,
    FOnationalFishingActivity, FOvalidity, FOcatchReg, FOmetier6, FOsampled,
    SScatchFraction
  ) %>%
  summarise(number_hauls = sum(!is.na((FOsequenceNumber))))


## SIRENO summary ----
sireno_summary <- hauls_catches %>%
  select(c(ESTRATO_TECNICO, ESTRATO_RIM, COD_MAREA, COD_LANCE, VALIDO, MUESTREADO)) %>%
  unique() %>%
  group_by(ESTRATO_TECNICO, ESTRATO_RIM, VALIDO, MUESTREADO) %>%
  summarise(number_hauls = length(COD_LANCE))


## number of hauls by rim stratum ----
hauls_summary <- get_hauls_summary_h1()


## number of trips by rim stratum ----
trips_summary <- get_trips_summary_h1()


## number of individuals by species ----
ind_by_sp <- get_ind_by_sp_summary_h1()